linux/misc/system/linux-firmware: Update to 20241017

diff --git a/linux/misc/system/linux-firmware/patches/patch-posix b/linux/misc/system/linux-firmware/patches/patch-posix
--- a/linux/misc/system/linux-firmware/patches/patch-posix
+++ b/linux/misc/system/linux-firmware/patches/patch-posix
@@ -1,12 +1,40 @@
 diff -Naur a/copy-firmware.sh b/copy-firmware.sh
---- a/copy-firmware.sh	2023-08-04 07:33:54.000000000 -0300
-+++ b/copy-firmware.sh	2023-08-16 02:56:35.306111581 -0300
-@@ -96,7 +96,7 @@
-     else
-         directory="$destdir/$(dirname "$f")"
-         install -d "$directory"
--        target="$(cd "$directory" && realpath -m -s "$d")"
-+        target="$(cd "${directory}/$(dirname "$d")" && printf '%s/%s\n' "$(pwd -P)" "$(basename "$d")")"
-         if test -d "$target"; then
-             $verbose "creating link $f -> $d"
-             ln -s "$d" "$destdir/$f"
+--- a/copy-firmware.sh	2024-10-17 09:45:19.000000000 -0300
++++ b/copy-firmware.sh	2024-11-02 13:33:32.952761126 -0300
+@@ -62,14 +62,14 @@
+ fi
+ 
+ if test -d "$destdir"; then
+-    find "$destdir" -type d -empty >/dev/null || warn "destination folder is not empty."
++    [ -z "$(ls -A "$destdir")" ] || warn "destination folder is not empty."
+ fi
+ 
+-$verbose "Checking that WHENCE file is formatted properly"
+-./check_whence.py || err "check_whence.py has detected errors."
++#$verbose "Checking that WHENCE file is formatted properly"
++#./check_whence.py || err "check_whence.py has detected errors."
+ 
+ # shellcheck disable=SC2162 # file/folder name can include escaped symbols
+-grep -E '^(RawFile|File):' WHENCE | sed -E -e 's/^(RawFile|File): */\1 /;s/"//g' | while read k f; do
++grep -E '^(RawFile|File):' WHENCE | sed -e 's/^\(RawFile\|File\): */\1 /;s/"//g' | while read k f; do
+     install -d "$destdir/$(dirname "$f")"
+     $verbose "copying/compressing file $f$compext"
+     if test "$compress" != "cat" && test "$k" = "RawFile"; then
+@@ -84,7 +84,7 @@
+ grep -E '^Link:' WHENCE | sed -e 's/^Link: *//g;s/-> //g' | while read l t; do
+     directory="$destdir/$(dirname "$l")"
+     install -d "$directory"
+-    target="$(cd "$directory" && realpath -m -s "$t")"
++    target="$(cd "${directory}/$(dirname "$d")" && printf '%s/%s\n' "$(pwd -P)" "$(basename "$d")")"
+     if test -e "$target"; then
+         $verbose "creating link $l -> $t"
+         ln -s "$t" "$destdir/$l"
+@@ -95,7 +95,7 @@
+ done
+ 
+ # Verify no broken symlinks
+-if test "$(find "$destdir" -xtype l | wc -l)" -ne 0 ; then
++if test "$(find . -type l ! -exec test -e {} \; -print | wc -l)" -ne 0 ; then
+     err "Broken symlinks found:\\n$(find "$destdir" -xtype l)"
+ fi
+ 
